[phases.setup]
nixPkgs = [
    "chromium",
    "nss",
    "freetype",
    "freetype.dev",
    "fontconfig",
    "stdenv.cc.cc.lib"
]

[phases.install]
cmds = ["PUPPETEER_SKIP_DOWNLOAD=true npm install", "chmod +x start.sh"]

[start]
cmd = "./start.sh"
