[phases.setup]
nixPkgs = [
    "chromium",
    "nss",
    "freetype",
    "freetype.dev",
    "fontconfig",
    "stdenv.cc.cc.lib"
]

[phases.install]
cmds = ["PUPPETEER_SKIP_DOWNLOAD=true npm install"]

[start]
cmd = "sh -c 'export PUPPETEER_EXECUTABLE_PATH=$(which chromium) && node server.js'"
